# Generated by Django 3.1.2 on 2020-10-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.AlterModelOptions(
            name='ksiazki',
            options={'verbose_name': 'Ksiazki', 'verbose_name_plural': 'Ksiazki'},
        ),
    ]
