# Generated by Django 3.1.2 on 2020-10-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0003_ksiazki_kategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydawnictwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.AddField(
            model_name='ksiazki',
            name='wydawnictwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ksiazki.wydawnictwo'),
        ),
    ]
