# Generated by Django 3.1.2 on 2020-10-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0004_auto_20201013_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wydawnictwo',
            options={'verbose_name': 'Wydawnictwa', 'verbose_name_plural': 'Wydawnictwa'},
        ),
    ]
